name: citas_v2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.4

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  cloud_firestore: ^4.3.1
  google_sign_in: ^6.1.5
  image_picker: ^0.8.6
  firebase_storage: ^11.0.10
  universal_html: ^2.2.4
  intl: ^0.20.2
  file_picker: ^5.2.5
  cached_network_image: ^3.3.0
  flutter_cache_manager: ^3.3.1
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

assets:
  - assets/
