// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxAIl1O4loaXuZ9ol6FNbyLrcqFiP61Io',
    appId: '1:189919536490:web:a953da262d5af420797113',
    messagingSenderId: '189919536490',
    projectId: 'citasv2',
    authDomain: 'citasv2.firebaseapp.com',
    storageBucket: 'citasv2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDscmqU0lHcysJUdXEgC-EZyvRx93vmSM8',
    appId: '1:189919536490:android:6bb2d28db07c8fba797113',
    messagingSenderId: '189919536490',
    projectId: 'citasv2',
    storageBucket: 'citasv2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTzSsigfIxLfCL4dKaAPQK6XkdPbOUkw4',
    appId: '1:189919536490:ios:37e6727ff1496d1a797113',
    messagingSenderId: '189919536490',
    projectId: 'citasv2',
    storageBucket: 'citasv2.firebasestorage.app',
    iosBundleId: 'com.example.citasV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTzSsigfIxLfCL4dKaAPQK6XkdPbOUkw4',
    appId: '1:189919536490:ios:37e6727ff1496d1a797113',
    messagingSenderId: '189919536490',
    projectId: 'citasv2',
    storageBucket: 'citasv2.firebasestorage.app',
    iosBundleId: 'com.example.citasV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxAIl1O4loaXuZ9ol6FNbyLrcqFiP61Io',
    appId: '1:189919536490:web:01f9e7a227b9567b797113',
    messagingSenderId: '189919536490',
    projectId: 'citasv2',
    authDomain: 'citasv2.firebaseapp.com',
    storageBucket: 'citasv2.firebasestorage.app',
  );
}
